spring.application.name=book-store-spring-boot
spring.datasource.url=jdbc:mysql://localhost:3306/book_store_db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


jwt.expiration = 60000
jwt.secret =ae93412a3b936541c4b1bb34f423526d0c05286c9b80f3dbcf0b9a63603fbc5b
